name: CI
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: bash scripts/tests.sh
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath:  features/feature_*/
      # - uses: dorny/test-reporter@v1.5.0
      #   with:
      #     name: test-results
      #     path: features/feature_*/test-results.json
      #     reporter: flutter-json