name: CI
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: subosito/flutter-action@v2
      #   with:
      #     channel: "stable"
      #     cache: true
      # - run: bash scripts/tests.sh
      # - uses: axel-op/dart-package-analyzer@v3
      #   id: analysis
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     relativePath:  features/feature_login/
      - name: Testando
        run: |
          paths:
            - features/feature_home/
            - features/feature_login/
            - features/feature_splash/
            
          echo paths

      # - name: Check scores
      #   env:
      #     TOTAL: ${{ steps.analysis.outputs.total }}
      #     TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
      #   run: |
      #     PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
      #     if (( $PERCENTAGE < 50 ))
      #     then
      #       echo Score too low!
      #       exit 1
      #     fi

      # - uses: dorny/test-reporter@v1.5.0
      #   with:
      #     name: test-results
      #     path: features/feature_*/test-results.json
      #     reporter: flutter-json