name: Flutter
on: [push]
jobs:
  flutter-tet:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
      uses: actions/checkout@v2
      run: cd ../../
      run: pwd

      - name: test 2
      uses: actions/checkout@v2
      run: cd ../../../
      run: pwd

      - name: test 3
      run: cd ../../
      run: pwd

      - name: test 4
      run: cd ../../../
      run: pwd