name: Flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        cache: true
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Flutter testes
        run: bash tests.sh
        